# Generated by Django 6.0 on 2026-04-04 08:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(db_index=True, editable=False)),
                ('bill_code', models.CharField(db_index=True, editable=False, max_length=32)),
                ('bill_kind', models.CharField(choices=[('purchase', 'Receiving / purchase'), ('sale', 'Sale / issue'), ('adjustment', 'Stock adjustment')], default='purchase', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid / settled')], default='draft', max_length=20)),
                ('is_paid', models.BooleanField(default=False, help_text='When True, reference shows PA- prefix for unified bill display.')),
                ('supplier_reference', models.CharField(blank=True, help_text='Vendor bill / external reference when receiving.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_bills', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_bills', to='superadmin.fiscalyear')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_bills', to='superadmin.restaurant')),
            ],
            options={
                'ordering': ['-occurred_at', '-seq'],
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_num', models.PositiveIntegerField(db_index=True, default=1, editable=False, help_text='Auto-increment per restaurant (overwritten on create).')),
                ('name', models.CharField(max_length=255)),
                ('cp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Cost price (CP)')),
                ('sp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Selling price (SP)')),
                ('unit_type', models.CharField(choices=[('liter', 'Liter / liquid'), ('packed', 'Packed (cigarettes, bread, etc.)'), ('piece', 'Piece / count'), ('kg', 'Kg (vegetables, bulk)'), ('vegetable', 'Vegetables'), ('ingredient', 'Kitchen ingredient'), ('other', 'Other')], default='piece', max_length=20)),
                ('pieces_per_pack', models.PositiveIntegerField(blank=True, help_text='For packed goods: units per pack (e.g. 20 sticks).', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_items', to='superadmin.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'product_num'],
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit_sp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('movement', models.CharField(choices=[('add', 'In / add'), ('remove', 'Out / remove')], default='add', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.bill')),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='inventory.masteritem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_product_num', models.PositiveIntegerField(default=1)),
                ('next_bill_seq', models.PositiveIntegerField(default=1)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sequence', to='superadmin.restaurant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('restaurant', 'bill_code'), name='inventory_bill_unique_code_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='masteritem',
            index=models.Index(fields=['restaurant', 'name'], name='inventory_m_restaur_d34dfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='masteritem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'product_num'), name='inventory_masteritem_unique_product_num'),
        ),
    ]
