# Generated by Django 6.0 on 2026-04-04 08:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cash/bank paid to vendor for this bill (can be partial; rest is credit).', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Vendor discount on this bill (reduces what you owe).', max_digits=12),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='is_sold_as_menu',
            field=models.BooleanField(default=False, help_text='Sold to customers as a menu product (not only kitchen use).'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='is_used_as_ingredient',
            field=models.BooleanField(default=True, help_text='Used in kitchen / recipes / prep.'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='superadmin.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='inventory.vendor'),
        ),
    ]
