# Generated by Django 6.0 on 2026-04-04 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_vendor_bill_payment_menu_flags'),
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritem',
            name='show_on_public_site',
            field=models.BooleanField(default=True, help_text='When sold as menu, whether this item appears on the public menu API.'),
        ),
        migrations.AddField(
            model_name='restaurantsequence',
            name='next_vendor_payment_seq',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_kind',
            field=models.CharField(choices=[('purchase', 'Receiving / purchase'), ('purchase_return', 'Return to supplier'), ('sale', 'Sale / issue'), ('adjustment', 'Stock adjustment')], default='purchase', max_length=20),
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(db_index=True, editable=False)),
                ('payment_code', models.CharField(db_index=True, editable=False, max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_payments', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payments', to='superadmin.fiscalyear')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='superadmin.restaurant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-occurred_at', '-seq'],
            },
        ),
        migrations.CreateModel(
            name='VendorPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payment_allocations', to='inventory.bill')),
                ('vendor_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.vendorpayment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
