# Generated by Django 6.0 on 2026-04-04 10:08

from decimal import Decimal

from django.db import migrations, models
from django.db.models import F


def backfill_payment_splits(apps, schema_editor):
    Bill = apps.get_model("inventory", "Bill")
    VendorPayment = apps.get_model("inventory", "VendorPayment")
    Bill.objects.filter(amount_paid__gt=0).update(paid_cash=F("amount_paid"))
    VendorPayment.objects.filter(total_amount__gt=0).update(paid_cash=F("total_amount"))


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_vendor_payments_returns_public_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_bank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Part of amount_paid via bank transfer.', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Part of amount_paid from cash (purchase: out; return: refund received in cash).', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_esewa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Part of amount_paid via eSewa / wallet.', max_digits=12),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='image',
            field=models.ImageField(blank=True, help_text='One photo per product (menu / stock reference).', null=True, upload_to='inventory/products/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='paid_bank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='paid_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='paid_esewa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.RunPython(backfill_payment_splits, migrations.RunPython.noop),
    ]
