# Generated by Django 6.0 on 2026-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_image_and_payment_splits'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritem',
            name='sp_per_piece',
            field=models.BooleanField(default=False, help_text='Packed items only: if True, SP is per piece; CP stays per pack. If False, SP is per pack like CP.'),
        ),
    ]
