# Generated by Django 6.0 on 2026-04-04 12:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_product_image_and_payment_splits'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Optional photo for the category (e.g. section header).', null=True, upload_to='menu/categories/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='superadmin.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Menu categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('portion_label', models.CharField(blank=True, help_text='How it is sold, e.g. "1 pc", "250 g plate", "Half plate".', max_length=120)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Selling price (NPR)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Main photo for this menu line.', null=True, upload_to='menu/items/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_public_site', models.BooleanField(default=True, help_text='If off, hidden from the public menu API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Amount of this stock item for one menu portion (same unit as inventory).', max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_ingredient_lines', to='inventory.masteritem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menuitem')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'master_item'), name='menu_item_ingredient_unique_master')],
            },
        ),
    ]
